### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ha0ye** [ha0ye/portalDS#2]
Short-term goals:
- [ ] develop Drake plan version of workflow
- [ ] update Maizuru Rmarkdown
- [ ] round off tests
- [ ] implement simulations

Medium-term goals:
- [ ] develop and check alternative metrics
- [ ] compare against DLM approach for estimating dynamic Jacobians
- [ ] outline paper
- [ ] draft preprint
- [ ] split package components for archiving

Long-term goals:
- [ ] paper submission
- [ ] methods writeup
